const mongoose=require('mongoose')


const UserSchema=new mongoose.Schema({
    username:{
        type:String,
        required:true,
        min:3,
        max:50,
        unique:true
    },
    email:{
        type:String,
        required:true,
        max:50,
        unique:true
    },
    password:{
        type:String,
        required:true,
        max:6,
    },
    profilePicture:{
        type:String,
        default:""
    },
    description:{
        type:String,
        default:""
    },
    ontheWeb:{
        linkedin:{
            type:String,
            default:""
        },
        github:{
            type:String,
            default:""
        },
        facebook:{
            type:String,
            default:""
        },
        twitter:{
            type:String,
            default:""
        },
        instagram:{
            type:String,
            default:""
        },
        website:{
            type:String,
            default:""
        }
    },
    info:{
        highestEducation:{
            type:String,
            default:""
        },
        currentStatus:{
            type:String,
            default:""
        }
    },
    interests:{
        type:Array,
        default:[]
    },
    followers:{
        type:Array,
        default:[]
    }

})
module.exports=mongoose.model('Users',UserSchema);